#!/bin/bash
# Helper script to get a fresh JWT token for testing
# This will help you get valid auth and provider tokens from your browser session

echo "🔑 Getting Fresh Tokens from Browser"
echo "======================================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Open your browser and go to: http://localhost:5173"
echo "2. Make sure you're logged in with Google"
echo "3. Open Browser DevTools (F12 or Cmd+Option+I)"
echo "4. Go to the Console tab"
echo "5. Paste this code and press Enter:"
echo ""
echo "-----------------------------------"
echo "(async () => {"
echo "  const { data } = await window.supabase.auth.getSession();"
echo "  console.log('AUTH_TOKEN=\"Bearer ' + data.session.access_token + '\"');"
echo "  console.log('PROVIDER_TOKEN=\"' + (data.session.provider_token || 'NOT_CONNECTED') + '\"');"
echo "  console.log('\\n✅ Copy the above tokens and update test-my-calendar.sh');"
echo "})();"
echo "-----------------------------------"
echo ""
echo "6. Copy the AUTH_TOKEN and PROVIDER_TOKEN values"
echo "7. Update them in test-my-calendar.sh"
echo ""
echo "Note: Tokens expire after 1 hour, so you'll need to refresh them periodically"
echo ""
