#!/bin/bash

# Quick setup script for Groq API (Free Tier)

echo "🚀 Setting up Groq API for CatchUp..."
echo ""
echo "Groq provides FREE, ultra-fast AI inference with generous limits."
echo ""
echo "📝 Steps:"
echo "1. Visit: https://console.groq.com/keys"
echo "2. Sign up (free)"
echo "3. Create an API key"
echo "4. Copy the key"
echo ""
echo "Then run:"
echo "  supabase secrets set GROQ_API_KEY=your_key_here"
echo ""
echo "Models available (all free):"
echo "  - llama-3.1-70b-versatile (very capable, used by default)"
echo "  - mixtral-8x7b-32768 (good for long context)"
echo "  - llama-3.2-90b (newest Llama model)"
echo ""
echo "Rate limits (free tier):"
echo "  - 30 requests/minute"
echo "  - 14,400 requests/day"
echo ""
echo "More than enough for development! 🎉"
